### ISSUE TITLE
Cassandra and Fred Complete a Ride

### ISSUE THREAD

**Issue by CobeyH** [CobeyH/SENG-480A#183]
Track issue for Milestone 2 scenarios.
Steps for completion

Cassandra's Perspective
- [x] Cassandra adds a car to her profile (#157 #168 )
- [x] Cassandra just invited 4 ultimate players to her group
- [x] The group already has 8 people so she must pay to expand it (#91 )
- [x] Cassandra creates a ride and chooses a car (#72 )

Fred's Perspective
- [x] Fred creates a new pickup point (#166)
- [x] Everybody else joins the ride
- [x] Fred sees the absurd gas prices on the gas calculator (#88 )
- [x] Fred messages Cassandra for her E-Transfer information (#63 and chat within rides?)
