### ISSUE TITLE
Beta Scenario Steps

### ISSUE THREAD

**Issue by CobeyH** [CobeyH/SENG-480A#412]
* Feature name: Steps for Milestone 3 Demo

**Steve**
- [ ] Invite audience to participate
- [ ] Create an Account (pre-fill in registration data)
- [ ] Complete the Welcome tutorial
- [ ] Create a new group (make it public)

**Erin**
- [ ] Search for public group
- [ ] Create a ride as driver
