### ISSUE TITLE
Complete steps for scenario Carter creates an account and joins a group after being invited by Erin

### ISSUE THREAD

**Issue by MarcusDunn** [CobeyH/SENG-480A#67]
One of the scenarios we will walk through for [presentation 1](https://github.com/margaretstorey/startup2022/blob/main/milestone%201%20-%20proof%20of%20concept.md) (the other is #68)

- [x] Receives a link via SMS from Erin
- [x] They open to the registration page (#59)
- [x] Fill in registration page
- [x] They are greeted with the group preview (#64)
- [x] Click join group and they join the group
- [x] See a ride and join the ride as a driver (#70) (#72)
